#!/bin/sh

if [ "$#" -eq "0" ]
	then
		echo "usage: magic [challname]. Genius!"
		exit 1
else
	pwninit --no-template
	rm $1
	mv $1_patched $1
	#!/bin/bash 

    echo """from pwn import *

# Set up pwntools for the correct architecture
exe = \"./$1\"
libc = ELF(\"libc.so.6\")
context.binary = elf = ELF(exe)
context.log_level = \"debug\"
context.aslr = True

def start(argv=[], *a, **kw):
    '''Start the exploit against the target.'''
    if args.REMOTE:
        return remote(\"\", )
    if args.GDB:
        return gdb.debug([exe] + argv, gdbscript=gdbscript, *a, **kw)
    else:
        return process([exe] + argv, *a, **kw)

gdbscript = '''
    c
'''.format(**locals())

def sl(a): return r.sendline(a)
def s(a): return r.send(a)
def sa(a, b): return r.sendafter(a, b)
def sla(a, b): return r.sendlineafter(a, b)
def re(a): return r.recv(a)
def ru(a): return r.recvuntil(a)
def rl(): return r.recvline()
def i(): return r.interactive()

r = start()

r.interactive()
    """ > exp.py

fi
